effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_left_joint1
    - panda_left_joint2
    - panda_left_joint3
    - panda_left_joint4
    - panda_left_joint5
    - panda_left_joint6
    - panda_left_joint7
    - panda_right_joint1
    - panda_right_joint2
    - panda_right_joint3
    - panda_right_joint4
    - panda_right_joint5
    - panda_right_joint6
    - panda_right_joint7
  constraints:
    goal_time: 0.5
    panda_left_joint1:
      goal: 0.05
    panda_left_joint2:
      goal: 0.05
    panda_left_joint3:
      goal: 0.05
    panda_left_joint4:
      goal: 0.05
    panda_left_joint5:
      goal: 0.05
    panda_left_joint6:
      goal: 0.05
    panda_left_joint7:
      goal: 0.05
    panda_right_joint1:
      goal: 0.05
    panda_right_joint2:
      goal: 0.05
    panda_right_joint3:
      goal: 0.05
    panda_right_joint4:
      goal: 0.05
    panda_right_joint5:
      goal: 0.05
    panda_right_joint6:
      goal: 0.05
    panda_right_joint7:
      goal: 0.05
  gains:
    panda_left_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_left_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_left_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_left_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_left_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    panda_left_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_left_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}
    panda_right_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_right_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_right_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_right_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_right_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    panda_right_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_right_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}

panda_left_state_controller:
  type: franka_control/FrankaStateController
  arm_id: panda_left
  joint_names:
    - panda_left_joint1
    - panda_left_joint2
    - panda_left_joint3
    - panda_left_joint4
    - panda_left_joint5
    - panda_left_joint6
    - panda_left_joint7
  publish_rate: 30  # [Hz]

panda_right_state_controller:
  type: franka_control/FrankaStateController
  arm_id: panda_right
  joint_names:
    - panda_right_joint1
    - panda_right_joint2
    - panda_right_joint3
    - panda_right_joint4
    - panda_right_joint5
    - panda_right_joint6
    - panda_right_joint7
  publish_rate: 30  # [Hz]
