state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

franka_state_controller:
  type: franka_control/FrankaStateController
  arm_id: panda
  publish_rate: 30  # [Hz]
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

cartesian_impedance_example_controller:
  type: franka_example_controllers/CartesianImpedanceExampleController
  arm_id: panda
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
